name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (used to be lein deps)
      run: clj
    - name: Run tests (used to be lein test)
      run: clojure -X:dev:test
