name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare java
    - uses: actions/checkout@v4
    - with:
          distribution: 'zulu'
          java-version: '8'

    - name: Install clojure tools
    - uses: DeLaGuardo/setup-clojure@13.0
    - with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          cli: 1.10.1.693              # Clojure CLI based on tools.deps
        
    
    
    - name: Install dependencies
      run: clj -T:build uber
    - name: Run tests
      run: clj -X:test
